### PR TITLE
Fix cdx-select width problems below 462px viewport width

### PR DESCRIPTION
**Pull request by hasanakg**
Bug: T347168

### CODE REVIEW

**Comment by guergana** [comment]
I think it's best if @sai-san reviews this ticket.

**Review by sai-san — DISMISSED** [review]
LGTM! Will try to break this once the changes are reflected on staging 😈

**Comment by hasanakg** [comment]
> LGTM! Will try to break this once the changes are reflected on staging 😈

It's on staging right now, no mercy from now on 😈

**Review by sai-san — APPROVED** [review]
LGTM. You don't have to change your process: I can wait to verify when things are merged into development and available in the staging environment. This is of course unless you have doubts about the requirements or find any blockers during implementation. In that case, do not hesitate to pull me in. Thanks!

**Pull request merged**
