### PR TITLE
Switch to Node 18 (LTS)

### PR DESCRIPTION
**Pull request by micgro42**
Node 17 is End-of-Life since 2022-06-01. Still using it causes all sorts of logspam in the command line and in GitHub action logs, and risks undefined behavior.

Also, some actions were still using Node 16.

### CODE REVIEW

**Review by lucaswerkmeister — APPROVED** [review]
LGTM, but I just saw there’s also an `.nvmrc` with 16 in it – do you want to update that as well?

**Comment by micgro42** [comment]
> LGTM, but I just saw there’s also an `.nvmrc` with 16 in it – do you want to update that as well?

Oh, I assumed that wouldn't exist because we are using sail everywhere. Will update it as well.

**Comment by lucaswerkmeister** [comment]
I mean, I wouldn’t mind deleting it either, but I didn’t add it. As long as it has the same version as the docker-compose file and everything else, I guess the nvmrc doesn’t hurt.

**Comment by micgro42** [comment]
> I mean, I wouldn’t mind deleting it either, but I didn’t add it. As long as it has the same version as the docker-compose file and everything else, I guess the nvmrc doesn’t hurt.

Yeah. Anyway, now it is correct. We can delete it later, if we want.

**Review by lucaswerkmeister — APPROVED** [review]

**Pull request merged**
