### PR TITLE
Schedule Release PR

### PR DESCRIPTION
**Pull request by itamargiv**
This change adds a workflow to create a PR to make a production release of Mismatch Finder every two weeks approximately (on the 1st and 15th of every month) or on manual dispatch when required.

This PR can then be reviewed by the engineers, UX and Product, and either accepted and merged or rejected and closed.

Please see #712 for an example of such PR.

### CODE REVIEW

**Comment by chukarave** [comment]
Would this require adding any relevant documentation anywhere?

**Comment by itamargiv** [comment]
> Would this require adding any relevant documentation anywhere?

Yes, for now this is documented in our team doc, as this is a team workflow

**Review by chukarave — APPROVED** [review]
Let's go for it

**Review by hasanakg — APPROVED** [review]

**Comment by itamargiv** [comment]
Thank you!

**Pull request merged**
