### PR TITLE
Install @vue/composition-api in preparation for Pinia migration

### PR DESCRIPTION
**Pull request by guergana**
Bug: [T346137](https://phabricator.wikimedia.org/T346137)

### CODE REVIEW

**Review by itamargiv — APPROVED** [review]

**Review by itamargiv — CHANGES_REQUESTED** [review]
oops, sorry I accidentally approved but meant to leave a comment.

Looks good to me, but seems like we have browser test issues

**Comment by guergana** [comment]
> oops, sorry I accidentally approved but meant to leave a comment.
> 
> Looks good to me, but seems like we have browser test issues

Oh, noo, this was not ready for review. Should have marked it as draft, my bad. :sweat_smile:

**Review by hasanakg — APPROVED** [review]
Seems good for me, thanks!

**Review by itamargiv — APPROVED** [review]
LGTM, thanks

**Pull request merged**
